/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#83d99c",
        "primary-container": "#006837",
        "surface-bright": "#38393a",
        "on-surface": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#604100",
        "inverse-on-surface": "#2f3131",
        "on-secondary-fixed": "#261814",
        secondary: "#dac1ba",
        "surface-container-low": "#1a1c1c",
        "surface-tint": "#83d99c",
        "on-primary-fixed": "#00210e",
        surface: "#121414",
        "surface-variant": "#333535",
        tertiary: "#ffba3f",
        "inverse-primary": "#0b6d3b",
        "on-background": "#e2e2e2",
        "tertiary-container": "#795200",
        "on-error": "#690005",
        "secondary-container": "#564540",
        "tertiary-fixed-dim": "#ffba3f",
        "surface-container-high": "#282a2b",
        "outline-variant": "#3f4940",
        "on-secondary-fixed-variant": "#54433e",
        "error-container": "#93000a",
        "secondary-fixed": "#f7ddd6",
        primary: "#83d99c",
        "on-tertiary": "#432c00",
        "on-tertiary-container": "#ffc870",
        "on-secondary-container": "#cbb3ac",
        background: "#121414",
        "on-primary-container": "#8ee4a6",
        "primary-fixed": "#9ef6b6",
        "surface-dim": "#121414",
        "surface-container": "#1e2020",
        outline: "#899489",
        "inverse-surface": "#e2e2e2",
        "on-primary-fixed-variant": "#00522a",
        "on-secondary": "#3c2d28",
        error: "#ffb4ab",
        "surface-container-lowest": "#0c0f0f",
        "on-surface-variant": "#bec9be",
        "surface-container-highest": "#333535",
        "on-tertiary-fixed": "#281800",
        "tertiary-fixed": "#ffdeae",
        "on-primary": "#00391b",
        "secondary-fixed-dim": "#dac1ba",
        amber: "#ffb955",
        mint: "#5dd9d0",
      },
      spacing: {
        base: "8px",
        xl: "32px",
        lg: "24px",
        sm: "12px",
        gutter: "16px",
        xs: "4px",
        md: "16px",
        "container-margin": "20px",
        unit: "4px",
        "stack-lg": "24px",
        "stack-md": "16px",
        "container-padding": "20px",
        "stack-sm": "8px",
        "pb-safe": "env(safe-area-inset-bottom)",
      },
      fontFamily: {
        "headline-xl": ["Manrope"],
        "headline-lg": ["Manrope"],
        "label-md": ["Space Grotesk"],
        "body-md": ["Manrope"],
        "headline-md": ["Manrope"],
        "label-sm": ["Space Grotesk"],
        "body-lg": ["Manrope"],
        "headline-sm": ["Manrope"],
        "label-lg": ["Space Grotesk"],
        "headline-lg-mobile": ["Manrope"],
      },
    },
  },
  plugins: [],
};
